# Generated by Django 6.0.3 on 2026-04-13 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emargement',
            name='contenu',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('enseignant', 'Enseignant'), ('responsable', 'Responsable')], default='enseignant', max_length=20),
        ),
    ]
