# Generated by Django 6.0.3 on 2026-04-14 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_emargement_contenu_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=30)),
                ('volHoraire', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='cahier',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.module'),
        ),
        migrations.AddField(
            model_name='emargement',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.module'),
        ),
    ]
