# Generated by Django 6.0.3 on 2026-04-15 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_module_cahier_module_emargement_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='enseignant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='project.enseignant'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='filiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etudiants', to='project.classe'),
        ),
        migrations.AlterField(
            model_name='module',
            name='nom',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='volHoraire',
            field=models.IntegerField(null=True),
        ),
    ]
