# Generated by Django 6.0.3 on 2026-07-06 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_module_enseignant_alter_etudiant_filiere_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emargement',
            name='contenu',
        ),
    ]
