# Generated by Django 6.0.3 on 2026-07-07 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_remove_emargement_contenu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='enseignant',
        ),
    ]
