# Generated by Django 6.0.3 on 2026-07-07 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_remove_module_enseignant'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='enseignant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='project.enseignant'),
        ),
    ]
