# Generated by Django 6.0.3 on 2026-07-07 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_module_enseignant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='enseignant',
        ),
        migrations.AddField(
            model_name='module',
            name='enseignant',
            field=models.ManyToManyField(blank=True, related_name='modules', to='project.enseignant'),
        ),
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.classe')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.enseignant')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.module')),
            ],
            options={
                'unique_together': {('enseignant', 'module', 'classe')},
            },
        ),
    ]
