# Generated by Django 6.0.3 on 2026-07-07 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_remove_module_enseignant_module_enseignant_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='affectation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='module',
            name='enseignant',
        ),
        migrations.AddField(
            model_name='affectation',
            name='annee_universitaire',
            field=models.CharField(blank=True, default='2025-2026', max_length=20),
        ),
        migrations.RemoveField(
            model_name='affectation',
            name='classe',
        ),
    ]
