# Generated by Django 6.0.3 on 2026-07-07 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_alter_affectation_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='affectation',
            unique_together={('enseignant', 'module', 'annee_universitaire')},
        ),
    ]
