# Generated by Django 6.0.3 on 2026-07-12 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_alter_affectation_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Responsable',
        ),
    ]
