# Generated by Django 6.0.3 on 2026-07-12 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_delete_responsable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absence',
            name='motif',
        ),
    ]
