# Generated by Django 6.0.3 on 2026-07-13 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_remove_absence_motif'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='affectation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='affectation',
            name='classe',
            field=models.ForeignKey(blank=True, default=7, on_delete=django.db.models.deletion.CASCADE, to='project.classe'),
        ),
    ]
