# Generated by Django 6.0.3 on 2026-07-13 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_alter_affectation_unique_together_affectation_classe'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='affectation',
            unique_together={('enseignant', 'module', 'annee_universitaire', 'classe')},
        ),
    ]
