# Generated by Django 6.0.3 on 2026-07-24 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_alter_affectation_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='emargement',
            name='classe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.classe'),
        ),
        migrations.AddField(
            model_name='module',
            name='nhCm',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='nhTd',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='nhTp',
            field=models.IntegerField(null=True),
        ),
    ]
