# Generated by Django 6.0.3 on 2026-07-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_emargement_classe_module_nhcm_module_nhtd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
