# Generated by Django 6.0.3 on 2026-07-30 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_classe_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='nhCm',
        ),
        migrations.RemoveField(
            model_name='module',
            name='nhTd',
        ),
        migrations.RemoveField(
            model_name='module',
            name='nhTp',
        ),
        migrations.AddField(
            model_name='module',
            name='heures_cm',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Heure CM'),
        ),
        migrations.AddField(
            model_name='module',
            name='heures_td',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Heures TD'),
        ),
        migrations.AddField(
            model_name='module',
            name='heures_tp',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Heures TP'),
        ),
    ]
