# Generated by Django 6.0.3 on 2026-08-13 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_remove_module_nhcm_remove_module_nhtd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='filiere',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='classe',
            name='niveau',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='nom',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='prenom',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='telephone',
            field=models.CharField(max_length=9),
        ),
    ]
