# Generated by Django 6.0.3 on 2026-08-15 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_alter_classe_filiere_alter_classe_niveau_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cahier',
            name='emargement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cahier_texte', to='project.emargement'),
        ),
    ]
