# Generated by Django 6.0.3 on 2026-08-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_cahier_emargement'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='code',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
