# Generated by Django 6.0.3 on 2026-08-15 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0020_module_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='code',
        ),
    ]
