# Generated by Django 6.0.3 on 2026-08-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0022_assistantepedagogique'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
