# Generated by Django 6.0.3 on 2026-08-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0023_module_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
